### ISSUE TITLE
Training on synthetic data

### ISSUE THREAD

**Issue by abylikhsanov** [cqylunlun/GLASS#11]
Hi,

I was experimenting with synthetic data of metal parts and here is the example from the training:

![023](https://github.com/user-attachments/assets/18ab6f20-2cd7-424a-8134-100847eda133)

The mask shows some scratches but I believe the light reflection is being treated as anomaly.

**Comment by cqylunlun** [comment]
Based on your current visualization results, we guess that this may be due to the defects being too subtle. The scale of illumination variation in the current samples might be greater than the actual difference between the anomalous and normal regions. For the examples of anomalies that can be detected by our algorithm, you may refer to the [MVTec AD, VisA, MPDD](https://github.com/cqylunlun/GLASS?tab=readme-ov-file#data-preparation), and [WFDD](https://github.com/cqylunlun/GLASS?tab=readme-ov-file#dataset-release) datasets.

**Comment by abylikhsanov** [comment]
Undestand. Am I correct to assume that GLASS only needs "good" data with no defects from various angles to effectively detect anomalies during inference?

I am just experimenting with synthetic data that are only good

**Comment by cqylunlun** [comment]
Close to correct! Based on the academic definition of anomaly detection, the training of GLASS is conducted utilizing only "good" data. During the inference stage, GLASS should have the ability to detect any samples without the limitation of defect types.
