### ISSUE TITLE
Change input size

### ISSUE THREAD

**Issue by shiomi326** [cqylunlun/GLASS#9]
Hi Thanks for your great repo.
I want to increase the input size. Like 512. Where do I need to change?

I know that I need to change arguments.
```
--resize 288
--image 288
```

But you set specific size in
```
def distribution_judge(img, name):

      img_ = cv2.resize(img, (289, 289))
```      
So I need to change that or this methods need to use 288 size?
Thanks.

**Comment by cqylunlun** [comment]
Thank you for your recognition. If you want to increase the input size to 512x512, you only need to modify arguments as follows:
```
--resize 512
--imagesize 512
```
Since `distribution_judge` does not affect the preprocessing of the training images, there is no need for any changes. For the purpose of this function or the selection of different variants, please refer to [#6-1](https://github.com/cqylunlun/GLASS/issues/6#issuecomment-2252906393). Additionally, if your images are not square-shaped and you wish to output results in the original dimensions, you can refer to [#6-2](https://github.com/cqylunlun/GLASS/issues/6#issuecomment-2269494430).

**Comment by shiomi326** [comment]
Thanks for the detailed description and quick response.
I will give that a try!

**Comment by shiomi326** [comment]
It worked fine. Thank you @cqylunlun
